name: i_jmu
description: i-JMU（i集大）
homepage: 'https://github.com/openjmu/i-jmu'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=2.2.3'

dependencies:
  flutter:
    sdk: flutter
  # 语言支持内建，使用 SDK 内置的版本
  flutter_localizations:
    sdk: flutter

  # Android Intent
  android_intent_plus: ^1.0.2
  # 加密
  crypto: ^3.0.1
  # 设备信息
  device_info: ^2.0.2
  # 网络请求
  dio: ^4.0.0
  # 快速实现对象比较
  equatable: ^2.0.3
  # 以 Overlay 实现的全局悬浮，包括普通的 Toast
  oktoast: ^3.0.0
  # 文件操作
  open_file: ^3.2.1
  # 软件包信息解析
  package_info_plus: ^1.0.3
  # 原生路径处理
  path_provider: ^2.0.1
  # 权限管理
  permission_handler: ^8.1.4+2
  # 图库管理
  photo_manager: ^1.3.1
  # 通过 URL 进行唤起
  url_launcher: ^6.0.9
  # UUID
  uuid: ^3.0.4

  # 数据存储
  hive: ^2.0.4
  hive_flutter: ^1.1.0

### 开发时使用的包，不会进入最终生产
dev_dependencies:
  args: ^2.2.0
  build_runner: ^2.0.6
  # 数据存储 Type Adapter 生成
  hive_generator: ^1.1.0
  # Json Model <=> 序列化生成库
  json_serializable: ^4.1.4

flutter:
  uses-material-design: true
