name: i_jmu
description: i-JMU（i集大）
homepage: 'https://github.com/openjmu/i-jmu'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.13.0 <3.0.0'
  flutter: '>=2.2.3'

dependencies:
  flutter:
    sdk: flutter
  # 语言支持内建，使用 SDK 内置的版本
  flutter_localizations:
    sdk: flutter

  # Android Intent
  android_intent_plus: ^2.0.0
  # Android Scheme 获取 App 名称
  android_scheme_search: ^1.0.1
  # Dio Cookie 容器
  cookie_jar: ^3.0.0
  # 加密
  crypto: ^3.0.1
  # 设备信息
  device_info: ^2.0.2
  # 网络请求
  dio: ^4.0.0
  # Dio Cookie 管理
  dio_cookie_manager: ^2.0.0
  # 快速实现对象比较
  equatable: ^2.0.3
  # 注解路由的注解库
  ff_annotation_route_library: ^2.0.1
  # WebView
  flutter_inappwebview: ^5.3.2
  # 处理 SVG 资源
  flutter_svg: ^0.22.0
  # 以 Overlay 实现的全局悬浮，包括普通的 Toast
  oktoast: ^3.1.1
  # 文件操作
  open_file: ^3.2.1
  # 软件包信息解析
  package_info_plus: ^1.0.6
  # 原生路径处理
  path_provider: ^2.0.2
  # 权限管理
  permission_handler: ^8.1.4+2
  # 图库管理
  photo_manager: ^1.3.1
  # 状态管理
  provider: ^6.0.0
  # 通过 URL 进行唤起
  url_launcher: ^6.0.9
  # UUID
  uuid: ^3.0.4
  # 视频播放
  video_player: ^2.1.12

  # 上拉加载和下拉刷新
  loading_more_list: ^4.1.0
  pull_to_refresh_notification: ^2.1.0

  # 数据存储
  hive: ^2.0.4
  hive_flutter: ^1.1.0

### 开发时使用的包，不会进入最终生产
dev_dependencies:
  args: ^2.2.0
  build_runner: ^2.1.1
  # 数据存储 Type Adapter 生成
  hive_generator: ^1.1.0
  # Json Model <=> 序列化生成库
  json_serializable: ^4.1.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/icons/
    - assets/placeholder/
