// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/material.dart';
import 'package:ff_annotation_route_library/ff_annotation_route_library.dart';
import 'package:flutter/widgets.dart';
import 'pages/login_page.dart';
import 'pages/main_page.dart';

// ignore_for_file: prefer_const_literals_to_create_immutables,unused_local_variable,unused_import
FFRouteSettings getRouteSettings({
  required String name,
  Map<String, dynamic>? arguments,
}) {
  final Map<String, dynamic> safeArguments =
      arguments ?? const <String, dynamic>{};
  switch (name) {
    case 'jmu://login-page':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: LoginPage(
          key: asT<Key?>(safeArguments['key']),
        ),
        routeName: '登录页',
      );
    case 'jmu://main-page':
      return FFRouteSettings(
        name: name,
        arguments: arguments,
        widget: MainPage(
          key: asT<Key?>(safeArguments['key']),
        ),
        routeName: '首页',
      );
    default:
      return const FFRouteSettings(name: '404', routeName: '404_page');
  }
}
