// GENERATED CODE - DO NOT MODIFY MANUALLY
// **************************************************************************
// Auto generated by https://github.com/fluttercandies/ff_annotation_route
// **************************************************************************

import 'package:flutter/widgets.dart';

const List<String> routeNames = <String>[
  'jmu://home-page',
  'jmu://login-page',
  'jmu://search-page',
  'jmu://splash-page',
  'jmu://web-view',
];

class Routes {
  const Routes._();

  /// '首页'
  ///
  /// [name] : 'jmu://home-page'
  ///
  /// [routeName] : '首页'
  ///
  /// [constructors] :
  ///
  /// HomePage : [Key? key]
  static const _JmuHomePage jmuHomePage = _JmuHomePage();

  /// '登录页'
  ///
  /// [name] : 'jmu://login-page'
  ///
  /// [routeName] : '登录页'
  ///
  /// [constructors] :
  ///
  /// LoginPage : [Key? key]
  static const _JmuLoginPage jmuLoginPage = _JmuLoginPage();

  /// '搜索页'
  ///
  /// [name] : 'jmu://search-page'
  ///
  /// [routeName] : '搜索页'
  ///
  /// [constructors] :
  ///
  /// SearchPage : [Key? key, String? keyword]
  static const _JmuSearchPage jmuSearchPage = _JmuSearchPage();

  /// '闪屏页'
  ///
  /// [name] : 'jmu://splash-page'
  ///
  /// [routeName] : '闪屏页'
  ///
  /// [constructors] :
  ///
  /// SplashPage : [Key? key]
  static const _JmuSplashPage jmuSplashPage = _JmuSplashPage();

  /// '网页浏览'
  ///
  /// [name] : 'jmu://web-view'
  ///
  /// [routeName] : '网页浏览'
  ///
  /// [constructors] :
  ///
  /// InAppWebViewPage : [Key? key, String(required) url, String? title, bool withCookie, bool withAction, bool withNavigationControls, bool withScaffold, bool keepAlive]
  static const _JmuWebView jmuWebView = _JmuWebView();
}

class _JmuHomePage {
  const _JmuHomePage();

  String get name => 'jmu://home-page';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _JmuLoginPage {
  const _JmuLoginPage();

  String get name => 'jmu://login-page';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _JmuSearchPage {
  const _JmuSearchPage();

  String get name => 'jmu://search-page';

  Map<String, dynamic> d({Key? key, String? keyword}) => <String, dynamic>{
        'key': key,
        'keyword': keyword,
      };

  @override
  String toString() => name;
}

class _JmuSplashPage {
  const _JmuSplashPage();

  String get name => 'jmu://splash-page';

  Map<String, dynamic> d({Key? key}) => <String, dynamic>{
        'key': key,
      };

  @override
  String toString() => name;
}

class _JmuWebView {
  const _JmuWebView();

  String get name => 'jmu://web-view';

  Map<String, dynamic> d(
          {Key? key,
          required String url,
          String? title = '网页链接',
          bool withCookie = true,
          bool withAction = true,
          bool withNavigationControls = false,
          bool withScaffold = true,
          bool keepAlive = false}) =>
      <String, dynamic>{
        'key': key,
        'url': url,
        'title': title,
        'withCookie': withCookie,
        'withAction': withAction,
        'withNavigationControls': withNavigationControls,
        'withScaffold': withScaffold,
        'keepAlive': keepAlive,
      };

  @override
  String toString() => name;
}
